### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by on102-yamauchi-kazuhiro** [on102-yamauchi-kazuhiro/furima-35937#1]
#URL
https://furima-35937.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます！
確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **Basic認証を実装しましょう**
実装後、IDとパスワードをissueに記載しましょう。

- [ ] **必要な情報を適切に入力して「会員登録」ボタンを押すと、ユーザーの新規登録ができるようにしましょう**
新規登録ボタンを押しても、登録ページに遷移できません。

※上記により、今回動作確認ができませんでした。次回ご提出時に再度確認させていただきます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by on102-yamauchi-kazuhiro** [comment]
ありがとうございます。

下記の件、修正致しました。

#What
https://furima-35937.herokuapp.com/

- Basic認証
ID: furima-admin
PWD: 35937

- 新規登録ボタンから新規登録ページへ遷移

よろしくお願いいたします。

**Comment by takumi0530** [comment]
@on102-yamauchi-kazuhiro さん、再度ご提出ありがとうございます‼︎
動作の確認をしたところ、改めて修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **新規登録・ログイン共にエラーハンドリングができていること（入力に問題がある状態で「会員登録」または「ログイン」ボタンが押された場合、情報は受け入れられず、各ページでエラーメッセージが表示されることを確認）**
空欄があってもエラーメッセージが出力されませんでした。

- [ ] **必要な情報を適切に入力すると、新規登録/ログインができること**
情報を全て埋めましたが、登録できませんでした。エラーメッセージが出力されないため、どの項目の修正が必要か本番環境ではわかりかねますので、ご確認をお願いいたします。

**◾︎各情報に入れたもの**

**・ユーザー名**
```
平仮名
カタカナ
英数字
```
**・パスワード**
```
6文字
7文字以上
```
**※上記により、動作確認ができておりません。次回ご提出時に確認させていただきます。**

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A
