### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by on102-yamauchi-kazuhiro** [on102-yamauchi-kazuhiro/furima-35937#10]
- Heroku URL
→https://furima-35937.herokuapp.com/
- Basic認証
→ID: furima-admin
→PWD: 35937
- ユーザー情報
【ユーザー①】
User Name: sample
E-mail: sample@sample.com
PWD: Sample123
【ユーザー②】
User Name: furima太郎
E-mail: aaa@bbb.com
PWD: Sample123

よろしくお願い致します。

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **電話番号は、10桁以上11桁以内の半角数値のみ保存可能としましょう**
9桁以内でも保存されてしまいます。

- [x] **購入ページでエラーハンドリングを実装しましょう**
**（入力に問題がある状態で「購入」ボタンが押された場合、情報は受け入れられず、購入ページでエラーメッセージが表示されること）**
電話番号を9桁以内で入力したとき、エラーメッセージが表示されず購入できてしまいます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by on102-yamauchi-kazuhiro** [comment]
ありがとうございます。
上記の件、修正しました。

よろしくお願い致します。

**Comment by takumi0530** [comment]
@on102-yamauchi-kazuhiro さん、再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/125553386-270a1fc9-5fbd-4d51-9e59-cb03ae9caeb6.png)

**Comment by on102-yamauchi-kazuhiro** [comment]
ありがとうございました
